version: "3.3"

services:

  # MongoDB
  mongo:
    logging:
      driver: none
    image: mongo

  # Camera handling service
  user-manager:
    image: moreillon/user-manager-mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: user_manager_example
      MONGODB_COLLECTION: users
      AUTHENTICATION_API_URL: http://authentication
      DEFAULT_ADMIN_PASSWORD: admin
    ports:
      - "6001:80"

  authentication:
    image: moreillon/authentication-mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: user_manager_example
      MONGODB_COLLECTION: users
      JWT_SECRET: keyboardcat
    ports:
      - "6002:80"

  user-manager-front:
    image: moreillon/user-manager-mongo-front
    logging:
      driver: none
    environment:
      VUE_APP_USER_MANAGER_API_URL: http://192.168.1.2:6001
      VUE_APP_AUTHENTICATION_API_URL: http://192.168.1.2:6002
    ports:
      - "6003:80"
