version: "3.3"

services:

  mongo:
    logging:
      driver: none
    image: mongo

  user-manager:
    image: moreillon/user-manager-mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: user_manager_example
      MONGODB_COLLECTION: users
      AUTHENTICATION_API_URL: http://authentication
      DEFAULT_ADMIN_PASSWORD: admin

  authentication:
    image: moreillon/authentication-mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: user_manager_example
      MONGODB_COLLECTION: users
      JWT_SECRET: keyboardcat

  user-manager-front:
    image: moreillon/user-manager-mongo-front
    logging:
      driver: none
    environment:
      VUE_APP_USER_MANAGER_API_URL: /proxy/user-manager
      VUE_APP_AUTHENTICATION_API_URL: /proxy/authentication

  api-proxy:
    image: moreillon/api-proxy
    environment:
      PROXY_ROOT: http://user-manager-front
      PROXY_AUTHENTICATION: http://authentication
      PROXY_USER_MANAGER: http://user-manager
    ports:
      - 7539:80
